server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: catalog-service
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
