server:
  port: ${PORT:${SERVER_PORT:0}}
  
idRandom: ${random.value}

spring:
  application:
    name: catalog-service  
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: catalog
      port: 27018
      
queue:
  serie:
    name: SerieQueue
  movie:
    name: MovieQueue
    
message: hello from catalog-service

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      getGenreOnline:
        allowHealthIndicatorToFail: false
        registerHealthIndicator: true
        slidingWindowType: TIME_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      getGenreOnline:
        maxAttempts: 3
        waitDuration: 1000
        retryExceptions:
          - feign.FeignException$InternalServerError
